spring:
  application:
    name: market
  datasource:
    url: jdbc:h2:mem:market;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
        enabled: true
  token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  kafka:
    enabled: ${KAFKA_ENABLED:true}
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: group-test
test:
  topic: test-topic

security:
  enabled: false